spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    password: 123456
    url: jdbc:oracle:thin:@localhost:1521/XE
    username: rishabh
  jpa:
    properties:
      hibernate:
       format_sql:true
       show_true
  mvc:
   view:
      prefix: /views/
      suffix: .jsp 
server:
  port: 8080
  servlet:
    context-path: /phoneBook
   
